# -*- coding: utf-8 -*-
"""Classification1 LR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/180B0Kijjsk_-nMWFX47GzfdQaRgrNIv3
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

diabetes = pd.read_csv('diabetes.csv')

diabetes.head()

from sklearn.model_selection import train_test_split

X=diabetes.drop('Outcome',axis=1)
Y=diabetes['Outcome']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.30, random_state=50)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train,Y_train)

Y_pred=model.predict(X_test)

from sklearn.metrics import accuracy_score

score=accuracy_score(Y_test,Y_pred)

score